### ISSUE TITLE
Unexpected results with from_hex method and demo page

### ISSUE THREAD

**Issue by marcstober** [c0bra/color-scheme-js#6]
Hi,

Maybe I'm not understanding how this works, but I'm getting unexpected results with the from_hex method.

For example, if I input "ff0000" which is red, I get a hue of 0, which is OK:

```
var scheme = new ColorScheme;
scheme.from_hex("ff0000");
console.log(scheme.col[0].hue); // 0
```

However, if I input "00aa00", which is green, I also get a hue of 0. I'd expect it to be around 180 or maybe 0.5 since green is the opposite of red on the classic color wheel.

I see the same issue if I enter a hex value and click "set" on the demo page.

Is this a bug?

**Comment by bsebastian86** [comment]
Hi, seems this is a two year old issue that was unaddressed.

I noticed that this was giving the wrong results also, even on the demo page. Can you please tell me how to fix this? Thanks.

**Comment by c0bra** [comment]
@bsebastian86 it looks like there's something being calculated incorrectly in rgb2hsv, however when I plug in different implementations, like this one: https://gist.github.com/mjackson/5311256, I still get an incorrect hue of 0 for the first color.

I checked Color::Scheme itself and it correctly returns 180 for the first color's hue. Its code for rgb2hsv hasn't changed in 11 years: https://github.com/rjbs/Color-Scheme/blob/master/lib/Color/Scheme.pm#L260 

At this point I'm not sure where the issue lies... 😕

**Comment by c0bra** [comment]
@bsebastian86 thanks for that tip, and sorry for the delay.

I finally found a way to convert rgb to ryb so it looks like the demo page from from_hex method is working properly now.
